apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mbh1rygwc-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mbh1rygwc-go 
  name: mbh1rygwc-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mbh1rygwc-go 
